baseurl:
title: Z-Hat
subtitle: Finding better representations
author: pragmanym
simple_search: http://google.com/search
description: A (we)blog devoted to finding better representations
name: zhat
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
future: true
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
plugins:
  - jekyll-target-blank

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true