url: danabo.github.io/zhat
title: Z-Hat
subtitle: Finding better representations
author: pragmanym
simple_search: http://google.com/search
description: A (we)blog devoted to finding better representations
name: zhat
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
kramdown:
  hard_wrap: true
  math_engine: null   # See https://github.com/gettalong/kramdown/issues/342 and https://github.com/jekyll/jekyll/issues/6061
permalink: /articles/:title
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'LICENSE']
post:
  template: _post.txt
  extension: md
future: true
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
plugins:
  - jekyll-target-blank
keep_files: ['.git', 'CNAME', '_config.yml']

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: true